### ISSUE TITLE
Fails to build on OS X

### ISSUE THREAD

**Issue by ulope** [hopey-dishwasher/termpix#11]
```shell
○ cargo --version
cargo 0.9.0 (8fc3fd8 2016-02-29)
```

```shell
○ rustc --version
rustc 1.7.0
```

Log output:

```
○ cargo install --git https://github.com/hopey-dishwasher/termpix
    Updating git repository `https://github.com/hopey-dishwasher/termpix`
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading image v0.6.1
 Downloading rustc-serialize v0.3.17
 Downloading terminal_size v0.1.4
 Downloading ansi_term v0.7.2
 Downloading docopt v0.6.78
 Downloading png v0.4.1
 Downloading glob v0.2.10
 Downloading gif v0.7.0
 Downloading enum_primitive v0.1.0
 Downloading num v0.1.31
 Downloading byteorder v0.4.2
 Downloading bitflags v0.3.3
 Downloading flate2 v0.2.13
 Downloading libc v0.2.6
 Downloading inflate v0.1.0
 Downloading miniz-sys v0.1.7
 Downloading gcc v0.3.24
 Downloading rand v0.3.14
 Downloading lzw v0.9.0
 Downloading color_quant v1.0.0
 Downloading winapi v0.2.5
 Downloading kernel32-sys v0.1.4
 Downloading winapi-build v0.1.1
 Downloading regex v0.1.48
 Downloading strsim v0.3.0
 Downloading regex-syntax v0.2.2
 Downloading aho-corasick v0.4.1
 Downloading memchr v0.1.7
   Compiling inflate v0.1.0
   Compiling winapi v0.2.5
   Compiling winapi-build v0.1.1
   Compiling ansi_term v0.7.2
   Compiling strsim v0.3.0
   Compiling libc v0.2.6
   Compiling color_quant v1.0.0
   Compiling glob v0.2.10
   Compiling rustc-serialize v0.3.17
   Compiling byteorder v0.4.2
   Compiling rand v0.3.14
   Compiling memchr v0.1.7
   Compiling regex-syntax v0.2.2
   Compiling gcc v0.3.24
   Compiling bitflags v0.3.3
   Compiling kernel32-sys v0.1.4
   Compiling aho-corasick v0.4.1
   Compiling lzw v0.9.0
   Compiling gif v0.7.0
   Compiling terminal_size v0.1.4
   Compiling miniz-sys v0.1.7
   Compiling flate2 v0.2.13
   Compiling regex v0.1.48
   Compiling docopt v0.6.78
   Compiling num v0.1.31
   Compiling enum_primitive v0.1.0
   Compiling png v0.4.1
   Compiling image v0.6.1
   Compiling termpix v0.1.0 (https://github.com/hopey-dishwasher/termpix#52ef8b67)
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:65:32: 65:47 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:65         (Some(w), None) => (w, scale_dimension(w, orig_height, orig_width)),
                                                                                                   ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:65:32: 65:47 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:66:29: 66:44 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:66         (None, Some(h)) => (scale_dimension(h * 2, orig_width, orig_height), h * 2),
                                                                                                ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:66:29: 66:44 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:103:28: 103:43 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:103     let calculated_width = scale_dimension(target_height, orig_width, orig_height);
                                                                                                ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:103:28: 103:43 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:107:24: 107:39 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:107         (target_width, scale_dimension(target_width, orig_height, orig_width))
                                                                                            ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:107:24: 107:39 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 4 previous errors
failed to compile `termpix v0.1.0 (https://github.com/hopey-dishwasher/termpix#52ef8b67)`, intermediate artifacts can be found at `/Users/ulo/target-install`

Caused by:
  Could not compile `termpix`.
```

**Comment by Skuzzzy** [comment]
I also got a build fail on Linux Mint

`    Updating git repository `https://github.com/hopey-dishwasher/termpix`
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading lzw v0.9.0
 Downloading ansi_term v0.7.2
 Downloading aho-corasick v0.4.1
 Downloading flate2 v0.2.13
 Downloading rand v0.3.14
 Downloading regex v0.1.48
 Downloading miniz-sys v0.1.7
 Downloading inflate v0.1.0
 Downloading num v0.1.31
 Downloading rustc-serialize v0.3.17
 Downloading regex-syntax v0.2.2
 Downloading strsim v0.3.0
 Downloading image v0.6.1
 Downloading byteorder v0.4.2
 Downloading terminal_size v0.1.4
 Downloading docopt v0.6.78
 Downloading winapi-build v0.1.1
 Downloading glob v0.2.10
 Downloading color_quant v1.0.0
 Downloading gcc v0.3.24
 Downloading winapi v0.2.5
 Downloading enum_primitive v0.1.0
 Downloading gif v0.7.0
 Downloading libc v0.2.6
 Downloading bitflags v0.3.3
 Downloading png v0.4.1
 Downloading memchr v0.1.7
 Downloading kernel32-sys v0.1.4
   Compiling regex-syntax v0.2.2
   Compiling ansi_term v0.7.2
   Compiling lzw v0.9.0
   Compiling glob v0.2.10
   Compiling bitflags v0.3.3
   Compiling rustc-serialize v0.3.17
   Compiling byteorder v0.4.2
   Compiling gcc v0.3.24
   Compiling color_quant v1.0.0
   Compiling gif v0.7.0
   Compiling miniz-sys v0.1.7
   Compiling strsim v0.3.0
   Compiling winapi-build v0.1.1
   Compiling inflate v0.1.0
   Compiling kernel32-sys v0.1.4
   Compiling libc v0.2.6
   Compiling winapi v0.2.5
   Compiling memchr v0.1.7
   Compiling flate2 v0.2.13
   Compiling aho-corasick v0.4.1
   Compiling regex v0.1.48
   Compiling rand v0.3.14
   Compiling terminal_size v0.1.4
   Compiling num v0.1.31
   Compiling docopt v0.6.78
   Compiling enum_primitive v0.1.0
   Compiling png v0.4.1
   Compiling image v0.6.1
   Compiling termpix v0.1.0 (https://github.com/hopey-dishwasher/termpix#52ef8b67)
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:65:32: 65:47 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:65         (Some(w), None) => (w, scale_dimension(w, orig_height, orig_width)),
                                                                                                   ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:65:32: 65:47 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:66:29: 66:44 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:66         (None, Some(h)) => (scale_dimension(h * 2, orig_width, orig_height), h * 2),
                                                                                                ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:66:29: 66:44 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:103:28: 103:43 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:103     let calculated_width = scale_dimension(target_height, orig_width, orig_height);
                                                                                                ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:103:28: 103:43 help: run `rustc --explain E0425` to see a detailed explanation
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:107:24: 107:39 error: unresolved name `scale_dimension` [E0425]
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:107         (target_width, scale_dimension(target_width, orig_height, orig_width))
                                                                                            ^~~~~~~~~~~~~~~
.cargo/git/checkouts/termpix-ce32799183612466/master/src/main.rs:107:24: 107:39 help: run `rustc --explain E0425` to see a detailed explanation
error: aborting due to 4 previous errors
`

**Comment by hopey-dishwasher** [comment]
Dammit

Turns out just accepting and merging pull requests without manually verifying them is a bad idea. Sorry folks, I'll fix it presently.

**Comment by hopey-dishwasher** [comment]
Should be fixed now, my bad. I should really get some test suites or something going.
